export const ADD_PROJECT = 'ADD_PROJECT';
export const CLICK_REMOVE_PROJECT = 'CLICK_DELETE_PROJECT';
export const CLICK_NEW_PROJECT = 'CLICK_NEW_PROJECT';
export const PROJECT_NAME_EXISTS = 'PROJECT_NAME_EXISTS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';